name: Test Code

on:
   pull_request:
    branches:
        - main

jobs:
    testCode:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci
              if: success()

            - name: Run EsLint
              run: npm run lint

        